/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2012
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
package com.ericsson.oss.services.security.npam.api.job.modelentities;

public enum JobType {

    ROTATE_NE_ACCOUNT_CREDENTIALS("ROTATE_NE_ACCOUNT_CREDENTIALS", false),
    ROTATE_NE_ACCOUNT_CREDENTIALS_AUTOGENERATED("ROTATE_NE_ACCOUNT_CREDENTIALS_AUTOGENERATED", false),
    ROTATE_NE_ACCOUNT_CREDENTIALS_FROM_FILE("ROTATE_NE_ACCOUNT_CREDENTIALS_FROM_FILE", false),
    CREATE_NE_ACCOUNT("CREATE_NE_ACCOUNT", true),
    DETACH_NE_ACCOUNT("DETACH_NE_ACCOUNT", true),
    CHECK_AND_UPDATE_NE_ACCOUNT_CONFIGURATION("CHECK_AND_UPDATE_NE_ACCOUNT_CONFIGURATION", false);


    private final String jobTypeName;
    private final boolean isAssociatedToEvent;


    /**
     * 
     */
    JobType(final String jobTypeName, final boolean isAssociatedToEvent) {
        this.jobTypeName = jobTypeName;
        this.isAssociatedToEvent = isAssociatedToEvent;
    }

    /**
     * @return the jobTypeName
     */
    public String getJobTypeName() {
        return jobTypeName;
    }

    /**
     * @return the isAssociatedToEvent
     */
    public boolean isAssociatedEvent() {
        return isAssociatedToEvent;
    }
}